compatibility_date = "2026-03-017" 
compatibility_flags = ["nodejs_compat"]

name = "guoyi-messages"  
compatibility_date = "2026-03-09"

[[d1_databases]]
binding = "DB"  
database_name = "guoyi-messages"  

database_id = "a5482efb-0aea-4f9a-bfe5-152e2b408716"  

